import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="./output.css" rel="stylesheet" />
      </head>
      <body className={'bg-orange-200 p-3 text-base font-sans leading-normal' + inter.className}>
        {children}
      </body>

    </html>
  )
}
